-- Metadata only: no application rows, Auth hashes, tokens or MFA secrets.
select jsonb_build_object(
  'storagePolicies',(select coalesce(jsonb_agg(jsonb_build_object('table',tablename,'name',policyname,'permissive',permissive,'roles',roles,'cmd',cmd,'qual',qual,'check',with_check)),'[]') from pg_policies where schemaname='storage'),
  'buckets',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',name,'public',public,'limit',file_size_limit,'mimes',allowed_mime_types)),'[]') from storage.buckets),
  'externalTriggers',(select coalesce(jsonb_agg(pg_get_triggerdef(t.oid,true)),'[]') from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid join pg_namespace fn on fn.oid=p.pronamespace where n.nspname='auth' and fn.nspname='public' and not t.tgisinternal),
  'enums',(select coalesce(jsonb_agg(e),'[]') from(select t.typname as name,jsonb_agg(x.enumlabel order by x.enumsortorder) as labels from pg_type t join pg_namespace n on n.oid=t.typnamespace join pg_enum x on x.enumtypid=t.oid where n.nspname='public' group by t.typname)e),
  'tables',(select jsonb_agg(j) from(select c.relname as name,c.relrowsecurity as rls,
    (select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'nullable',not a.attnotnull,'generated',a.attgenerated,'identity',a.attidentity,'default',pg_get_expr(d.adbin,d.adrelid)) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped) as columns,
    (select coalesce(jsonb_agg(jsonb_build_object('name',k.conname,'kind',k.contype,'def',pg_get_constraintdef(k.oid,true))),'[]') from pg_constraint k where k.conrelid=c.oid) as constraints,
    (select coalesce(jsonb_agg(jsonb_build_object('name',i.relname,'def',pg_get_indexdef(i.oid))),'[]') from pg_index x join pg_class i on i.oid=x.indexrelid where x.indrelid=c.oid and not exists(select 1 from pg_constraint k where k.conindid=i.oid)) as indexes
    from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' order by c.relname)j),
  'functions',(select coalesce(jsonb_agg(jsonb_build_object('name',p.proname,'signature',p.oid::regprocedure::text,'def',pg_get_functiondef(p.oid)) order by p.proname),'[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prokind='f' and not exists(select 1 from pg_depend d where d.objid=p.oid and d.deptype='e')),
  'views',(select coalesce(jsonb_agg(jsonb_build_object('name',c.relname,'def',pg_get_viewdef(c.oid,true),'options',c.reloptions) order by c.relname),'[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='v'),
  'triggers',(select coalesce(jsonb_agg(pg_get_triggerdef(t.oid,true) order by t.tgname),'[]') from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and not t.tgisinternal),
  'policies',(select coalesce(jsonb_agg(jsonb_build_object('table',tablename,'name',policyname,'permissive',permissive,'roles',roles,'cmd',cmd,'qual',qual,'check',with_check)),'[]') from pg_policies where schemaname='public'),
  'grants',(select coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'role',coalesce(r.rolname,'PUBLIC'),'privilege',a.privilege_type)),'[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner)))a left join pg_roles r on r.oid=a.grantee where n.nspname='public' and c.relkind in('r','v') and (r.rolname in('anon','authenticated','service_role') or a.grantee=0)),
  'columnGrants',(select coalesce(jsonb_agg(jsonb_build_object('table',c.relname,'column',x.attname,'role',r.rolname,'privilege',a.privilege_type)),'[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute x on x.attrelid=c.oid cross join lateral aclexplode(x.attacl)a join pg_roles r on r.oid=a.grantee where n.nspname='public' and r.rolname in('anon','authenticated','service_role')),
  'functionGrants',(select coalesce(jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'role',coalesce(r.rolname,'PUBLIC'),'privilege',a.privilege_type)),'[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner)))a left join pg_roles r on r.oid=a.grantee where n.nspname='public' and p.prokind='f' and not exists(select 1 from pg_depend d where d.objid=p.oid and d.deptype='e') and (r.rolname in('anon','authenticated','service_role') or a.grantee=0))
) as catalog;
